variables:
  APP_NAME: rn-iii-frontend

include:
  - project: "mpib/chm/common/deploy-pipeline"
    ref: "1.5.0"
    file: "react-app.yml"

build:
  extends: .build
  before_script:
    - cp $CI_PROJECT_DIR/$CHILD_PIPELINE_EXECUTION_CONTEXT $CI_PROJECT_DIR
