variables:
  APP_NAME: rn-iii-backend

include:
  - project: "mpib/chm/common/deploy-pipeline"
    ref: "apv_18"
    file: "python-app.yml"

init:
  extends: .init-stage
  after_script:
    - echo "Copying files from subdirectory to root directory"
    - cp -r $CHILD_PIPELINE_EXECUTION_CONTEXT/* ./
    - rm -rf frontend
    - rm -rf backend
#    - ls -R
  artifacts:
    paths:
      - ./
