variables:
  DEPLOYMENT_VARS: "MONGO_URL, DATABASE_NAME, N_GENERATIONS, SIMULATE_FIRST_GENERATION"
  APP_NAME: rn-iii-backend
  N_GENERATIONS: 3
  SIMULATE_FIRST_GENERATION: "True"

include:
  - project: "mpib/chm/common/deploy-pipeline"
    ref: "1.5.1"
    file: "python-app.yml"

init:
  extends: .init-stage
  after_script:
    - echo "Copying files from subdirectory to root directory"
    - cp -r $CHILD_PIPELINE_EXECUTION_CONTEXT/* ./
    - rm -rf frontend
    - rm -rf backend
#    - ls -R
# set environment variables for experiment configuration
    - echo "DATABASE_NAME=${APP_NAME}-$(git log --pretty='format:%C(auto)%ad' --date=format:%Y%m%d-%H%M%S -n 1)" >>build.env
    - echo "N_GENERATIONS=${N_GENERATIONS}" >>build.env
    - echo "SIMULATE_FIRST_GENERATION=${SIMULATE_FIRST_GENERATION}" >>build.env
    - cat build.env
  artifacts:
    paths:
      - ./
