variables:
  APP_NAME: rn-iii-te
  DOCKER_FILE: docker/Dockerfile
  DOCKER_TARGET: task-explorer
  FRONTEND_URL: https://rn-iii-frontend.eks-test-default.mpg-chm.com
  MAIN_URL: https://rn-iii-task-explorer.eks-test-default.mpg-chm.com

include:
  - project: "mpib/chm/common/deploy-pipeline"
    ref: "1.8.2"
    file: "python-app.yml"

init:
  extends: .init-stage
  script:
    - apk add --no-cache git
    - source deploy-pipeline/build_env.sh
    - ls -lt deploy-pipeline
    # - deploy-pipeline/display_env.sh

docker:
  extends: .docker-stage
  script:
    - ls -lt
    - ls -lt deploy-pipeline
    - /bin/sh deploy-pipeline/docker_login.sh
    - echo "${IMAGE_NAME}:${IMAGE_TAG}"
    - DOCKER_TARGET_ARG=$( [ -z "$DOCKER_TARGET" ] && echo "" || echo "--target ${DOCKER_TARGET}" )
    - /kaniko/executor
      --context "$CI_PROJECT_DIR"
      --dockerfile "${DOCKER_FILE}"
      ${DOCKER_TARGET_ARG}
      --destination "${REGISTRY_URL}/${DOCKER_REGISTRY_PREFIX}/${IMAGE_NAME}:${IMAGE_TAG}"
