variables:
  APP_NAME: rn-iii-frontend
  BACKEND_URL: https://rn-iii-backend.eks-test-default.mpg-chm.com

include:
  - project: "mpib/chm/common/deploy-pipeline"
    ref: "1.5.0"
    file: "react-app.yml"

init:
  extends: .init-stage
  after_script:
    - echo "Copying files from subdirectory to root directory"
    - cp -r $CHILD_PIPELINE_EXECUTION_CONTEXT/* ./
    - rm -rf $CHILD_PIPELINE_EXECUTION_CONTEXT
    - ls -R
  artifacts:
    paths:
      - ./
