variables:
  APP_NAME: rn-iii-backend
  experiment_name: reward-network-iii-pilot-test-1
  rewrite_previous_data: true
  n_generations: 4

include:
  - project: "mpib/chm/common/deploy-pipeline"
    ref: "1.5.1"
    file: "python-app.yml"

init:
  extends: .init-stage
  after_script:
    - echo "Copying files from subdirectory to root directory"
    - cp -r $CHILD_PIPELINE_EXECUTION_CONTEXT/* ./
    - rm -rf frontend
    - rm -rf backend
#    - ls -R
  artifacts:
    paths:
      - ./
