variables:
  APP_NAME: rn-iii-frontend
  BACKEND_URL: https://rn-iii-backend.eks-test-default.mpg-chm.com

include:
  - project: "mpib/chm/common/deploy-pipeline"
    ref: "1.5.0"
    file: "react-app.yml"

init:
  extends: .init-stage
  after_script:
    - cp -r $CHILD_PIPELINE_EXECUTION_CONTEXT/* ./
    - rm -rf frontend
    - rm -rf backend
#    - ls -R
  artifacts:
    paths:
      - ./

build:
  extends: build
  before_script:
    - rm -rf frontend
    - rm -rf backend

docker:
  extends: .docker-stage
  before_script:
    - rm -rf frontend
    - rm -rf backend
    - ls -R
