variables:
  DEPLOYMENT_VARS: "MONGO_URL, DATABASE_NAME, N_GENERATIONS, SIMULATE_FIRST_GENERATION"
  APP_NAME: rn-iii-backend

include:
  - project: "mpib/chm/common/deploy-pipeline"
    ref: "1.5.1"
    file: "python-app.yml"

init:
  extends: .init-stage
  after_script:
    - echo "Copying files from subdirectory to root directory"
    - cp -r $CHILD_PIPELINE_EXECUTION_CONTEXT/* ./
    - rm -rf frontend
    - rm -rf backend
    - echo "DATABASE_NAME=${APP_NAME}-$(git log --pretty='format:%C(auto)%ad' --date=format:%Y%m%d-%H%M%S -n 1)" >>build.env
# set environment variables for experiment configuration
    - cat build.env
#    - ls -R
  artifacts:
    paths:
      - ./
