variables:
  APP_NAME: rn-iii-backend
  EXPERIMENT_NAME: reward-network-iii-pilot-test
  N_GENERATIONS: 2
  REWRITE_PREVIOUS_DATA: "False"

include:
  - project: "mpib/chm/common/deploy-pipeline"
    ref: "1.5.1"
    file: "python-app.yml"

init:
  extends: .init-stage
  after_script:
    - echo "Copying files from subdirectory to root directory"
    - cp -r $CHILD_PIPELINE_EXECUTION_CONTEXT/* ./
    - rm -rf frontend
    - rm -rf backend
# set environment variables for experiment configuration
    - echo "EXPERIMENT_NAME=${EXPERIMENT_NAME}" >>build.env
    - echo "N_GENERATIONS=${N_GENERATIONS}" >>build.env
    - echo "REWRITE_PREVIOUS_DATA=${REWRITE_PREVIOUS_DATA}" >>build.env
    - cat build.env
#    - ls -R
  artifacts:
    paths:
      - ./
