variables:
  DEPLOYMENT_VARS: "MONGO_URL, EXPERIMENT_NAME, N_GENERATIONS, REWRITE_PREVIOUS_DATA"
  APP_NAME: rn-iii-backend

include:
  - project: "mpib/chm/common/deploy-pipeline"
    ref: "1.5.1"
    file: "python-app.yml"

init:
  extends: .init-stage
  after_script:
    - echo "Copying files from subdirectory to root directory"
    - cp -r $CHILD_PIPELINE_EXECUTION_CONTEXT/* ./
    - rm -rf frontend
    - rm -rf backend
# set environment variables for experiment configuration
#    - cat build.env
#    - ls -R
  artifacts:
    paths:
      - ./
