variables:
  APP_NAME: rn-iii-task-explorer
  DOCKER_FILE: docker/Dockerfile
  DOCKER_TARGET: task-explorer
  FRONTEND_URL: https://rn-iii-frontend.eks-test-default.mpg-chm.com
  MAIN_URL: https://rn-iii-task-explorer.eks-test-default.mpg-chm.com

include:
  - project: "mpib/chm/common/deploy-pipeline"
    ref: "1.8.2"
    file: "python-app.yml"
