version: "3.3"
services:
  app:
    image: app
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      PORT: 5000
      MONGO_URL: "mongodb://rw-ii-database:27017/"
    ports:
      - "5000:5000"
  database:
    image: mongo:4.0.8
    restart: unless-stopped
    command: mongod
    ports:
      - "27017:27017"
