version: "3.9"
services:
  database:
    image: mongo:4.0.8
    volumes:
      - data:/data/db
    restart: unless-stopped
    ports:
      - "27017:27017"

  fastapi: # backend
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./backend:/backend
    environment:
      PORT: 5040
      MONGO_URL: "mongodb://database:27017/"
      GENERATE_FRONTEND_TYPES: "false"
      # Environment variables for official FastAPI docker image
      APP_MODULE: "server:api"
      LOG_LEVEL: "debug"
      BACKEND_USER: "admin"
      BACKEND_PASSWORD: "admin"
    # start-reload.sh is a version of start.sh for development with live auto-reload
    command: ["uvicorn", "server:api", "--host", "0.0.0.0", "--port", "5000"]
    ports:
      - "5040:5040"
    depends_on:
      - database

  react: # frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
      - "9000:9000"
    volumes:
      - /usr/frontend/node_modules
      - ./frontend/static:/frontend/static
      - ./frontend/dist:/frontend/dist
      - ./frontend/src:/frontend/src
      - ./frontend/tsconfig.json:/frontend/tsconfig.json
      - ./frontend/webpack.config.js:/frontend/webpack.config.js
    environment:
      BACKEND_URL: "http://localhost:5040"
    stdin_open: true # to replicate `-it` mode in docker run
    tty: true # to replicate `-it` mode in docker run
    depends_on:
      - fastapi

  react-prod: # frontend
    build:
      context: .
      dockerfile: docker/Dockerfile-frontend
    ports:
      - "9090:80"

  react-storybook: # frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-storybook
    ports:
      - "6006:6006"
    restart: always
    volumes:
      - /usr/frontend/node_modules
      - ./frontend/src:/frontend/src
      - ./frontend/static:/frontend/static
      - ./frontend/.storybook:/frontend/.storybook
      - ./frontend/tsconfig.json:/frontend/tsconfig.json
      - ./frontend/webpack.config.js:/frontend/webpack.config.js
      - ./frontend/package.json:/frontend/package.json
      - ./.git:/.git
    # depends_on:
    #   - react

  task-explorer:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: task-explorer-dev
    environment:
      PORT: 5050
      FRONTEND_URL: "http://localhost:9000"
    volumes:
      - ./task_explorer/app:/app/task_explorer/app
      - ./task_explorer/environments:/app/task_explorer/environments
      - ./common:/app/common
    ports:
      - "5050:5050"
    command: streamlit run task_explorer/app/app.py --server.port=5050 --server.address=0.0.0.0

  task-exporer-prod:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: task-explorer
    environment:
      # FRONTEND_URL: "http://localhost:9090"
      FRONTEND_URL: https://rn-iii-frontend.eks-test-default.mpg-chm.com
    ports:
      - "5030:5000"
    depends_on:
      - react-prod

  common: # backend
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: base
    volumes:
      - .:/app/.
    depends_on:
      - database

volumes:
  data:
