version: "3.9"
services:
  database:
    image: mongo:4.0.8
    volumes:
      - data:/data/db
    restart: unless-stopped
    ports:
      - "27017:27017"

  backend: # backend
    build:
      context: .
      dockerfile: setup/docker/Dockerfile
      target: backend-dev
    volumes:
      - ./backend/app:/app/app
      - ./data:/app/app/data
      - ./backend/pytest.ini:/app/pytest.ini
    environment:
      MONGO_URL: "mongodb://database:27017/"
      GENERATE_FRONTEND_TYPES: "false"
      BACKEND_USER: "admin"
      BACKEND_PASSWORD: "admin"
    # start-reload.sh is a version of start.sh for development with live auto-reload
    command:
      [
        "uvicorn",
        "server:api",
        "--host",
        "0.0.0.0",
        "--port",
        "5000",
        "--reload",
      ]
    ports:
      - "5050:5000"
    depends_on:
      - database

  frontend: # frontend
    build:
      context: .
      dockerfile: setup/docker/Dockerfile-frontend-dev
    ports:
      - "9000:9000" # app
      - "6006:6006" # storybook
    volumes:
      - ./frontend/static:/frontend/static
      - ./frontend/dist:/frontend/dist
      - ./frontend/src:/frontend/src
      - ./frontend/tsconfig.json:/frontend/tsconfig.json
      - ./frontend/webpack.config.js:/frontend/webpack.config.js
      - ./frontend/gen_config.js:/frontend/gen_config.js
      - ./frontend/.storybook:/frontend/.storybook
    environment:
      BACKEND_URL: "http://0.0.0.0:5050"
    stdin_open: true
    tty: true
    command: ["npm", "run", "start"] # start app only
    # command: ["npm", "run", "start:both"] # start storybook and app
    depends_on:
      - backend

  streamlit:
    build:
      context: .
      dockerfile: setup/docker/Dockerfile
      target: streamlit-dev
    environment:
      PORT: 5050
      FRONTEND_URL: "http://localhost:9000"
      # FRONTEND_URL: https://rn-iii-frontend.eks-test-default.mpg-chm.com
    volumes:
      - ./streamlit/app:/app/streamlit/app
      - ./config:/app/config
      - ./common:/app/common
    ports:
      - "5050:5050"
    command: streamlit run streamlit/app/app.py --server.port=5050 --server.address=0.0.0.0 --server.fileWatcherType=watchdog
    depends_on:
      - frontend

  frontend-prod: # frontend
    build:
      context: .
      dockerfile: setup/docker/Dockerfile-frontend
    ports:
      - "9090:80"

  streamlit-prod:
    build:
      context: .
      dockerfile: setup/docker/Dockerfile
      target: streamlit
    environment:
      # FRONTEND_URL: "http://localhost:9090"
      FRONTEND_URL: https://rn-iii-frontend.eks-test-default.mpg-chm.com
    ports:
      - "5030:5000"
    depends_on:
      - frontend-prod

  all: # backend
    build:
      context: .
      dockerfile: setup/docker/Dockerfile
      target: all
    volumes:
      - .:/app/.
    depends_on:
      - database

volumes:
  data:
