version: "3.9"
services:
  database:
    image: mongo:4.0.8
    volumes:
      - data:/data/db
    restart: unless-stopped
    ports:
      - "27017:27017"

  fastapi: # backend
    build:
      context: .
      dockerfile: setup/docker/Dockerfile
    volumes:
      - ./backend:/backend
    environment:
      PORT: 5040
      MONGO_URL: "mongodb://database:27017/"
      GENERATE_FRONTEND_TYPES: "false"
      # Environment variables for official FastAPI docker image
      APP_MODULE: "server:api"
      LOG_LEVEL: "debug"
      BACKEND_USER: "admin"
      BACKEND_PASSWORD: "admin"
    # start-reload.sh is a version of start.sh for development with live auto-reload
    command: ["uvicorn", "server:api", "--host", "0.0.0.0", "--port", "5000"]
    ports:
      - "5040:5040"
    depends_on:
      - database

  react: # frontend
    build:
      context: .
      dockerfile: setup/docker/Dockerfile-frontend-dev
    ports:
      - "9000:9000" # app
      - "6006:6006" # storybook
    volumes:
      - ./frontend/static:/frontend/static
      - ./frontend/dist:/frontend/dist
      - ./frontend/src:/frontend/src
      - ./frontend/tsconfig.json:/frontend/tsconfig.json
      - ./frontend/webpack.config.js:/frontend/webpack.config.js
      - ./frontend/gen_config.js:/frontend/gen_config.js
      - ./frontend/.storybook:/frontend/.storybook
    environment:
      BACKEND_URL: "http://localhost:5040"
    stdin_open: true
    tty: true
    # command: ["npm", "run", "start"] # start app only
    command: ["npm", "run", "start:both"] # start storybook and app
    depends_on:
      - fastapi

  react-prod: # frontend
    build:
      context: .
      dockerfile: setup/docker/Dockerfile-frontend
    ports:
      - "9090:80"

  task-explorer:
    build:
      context: .
      dockerfile: setup/docker/Dockerfile
      target: task-explorer-dev
    environment:
      PORT: 5050
      FRONTEND_URL: "http://localhost:9000"
      # FRONTEND_URL: https://rn-iii-frontend.eks-test-default.mpg-chm.com
    volumes:
      - ./task_explorer/app:/app/task_explorer/app
      - ./config:/app/config
      - ./common:/app/common
    ports:
      - "5050:5050"
    command: streamlit run task_explorer/app/app.py --server.port=5050 --server.address=0.0.0.0
    depends_on:
      - react

  task-explorer-prod:
    build:
      context: .
      dockerfile: setup/docker/Dockerfile
      target: task-explorer
    environment:
      # FRONTEND_URL: "http://localhost:9090"
      FRONTEND_URL: https://rn-iii-frontend.eks-test-default.mpg-chm.com
    ports:
      - "5030:5000"
    depends_on:
      - react-prod

  common: # backend
    build:
      context: .
      dockerfile: setup/docker/Dockerfile
      target: base
    volumes:
      - .:/app/.
    depends_on:
      - database

volumes:
  data:
