---
apiVersion: v1
kind: Secret
metadata:
  name: airfoil-scoring-frontend
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockersecret }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airfoil-scoring-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airfoil-scoring-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: airfoil-scoring-frontend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: airfoil-scoring-frontend
          image: docker.gitlab.gwdg.de/mpib/chm/common/base-images/airfoilscoringfrontend:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: airfoil-scoring-frontend
---
