---
apiVersion: v1
kind: Service
metadata:
  name: airfoil-scoring-frontend
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: airfoil-scoring-frontend
  type: ClusterIP
  sessionAffinity: None
