{{- $main_url_base := default .Values.app.name .Values.app.main_url -}}
{{- $main_url_branch := eq .Values.branchName "master" | ternary "" (print "-" .Values.branchName) -}}
{{- $main_url := print $main_url_base $main_url_branch -}}

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: {{ include "deployment.fullname" . }}
spec:
  rules:
    - host: '{{ $main_url }}.eks-test-default.mpg-chm.com'
      http:
        paths:
          - backend:
              serviceName: {{ include "deployment.fullname" . }}
              servicePort: http
            path: /
  tls:
    - hosts:
        - '{{ $main_url }}.eks-test-default.mpg-chm.com'
