---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deployment.fullname" . }}{{ include "deployment.branchname" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockersecret }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deployment.fullname" . }}{{ include "deployment.branchname" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}
    helm.sh/deploymentname: {{ include "deployment.fullname" . }}{{ include "deployment.branchname" . }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ include "deployment.fullname" . }}{{ include "deployment.branchname" . }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "deployment.fullname" . }}{{ include "deployment.branchname" . }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ include "deployment.fullname" . }}{{ include "deployment.branchname" . }}
          image: docker.gitlab.gwdg.de/mpib/chm/common/base-images/airfoilscoringfrontend:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: {{ include "deployment.fullname" . }}{{ include "deployment.branchname" . }}
---
