---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment.fullname" . }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: {{ include "deployment.fullname" . }}
  type: ClusterIP
  sessionAffinity: None
