variables:
  APP_NAME: rn-iii-frontend
  BACKEND_URL: https://rn-iii-backend.eks-test-default.mpg-chm.com
  DOCKER_FILE: setup/docker/Dockerfile-frontend
  FRONTEND_PATH: frontend

include:
  - project: "mpib/chm/common/deploy-pipeline"
    ref: "1.8.5"
    file: "react-app.yml"

build:
  before_script:
    - cd $FRONTEND_PATH # Feature: make frontend path configurable
  cache:
    paths:
      - ${FRONTEND_PATH}/node_modules/ # Feature: make frontend path configurable

  artifacts:
    paths:
      - ${FRONTEND_PATH}/dist/ # Feature: make frontend path configurable
    expire_in: 1 week
