variables:
  DEPLOYMENT_VARS: "FRONTEND_URL"
  APP_NAME: rn-iii-te
  DOCKER_FILE: setup/docker/Dockerfile
  DOCKER_TARGET: streamlit
  FRONTEND_URL: https://rn-iii-frontend.eks-test-default.mpg-chm.com

include:
  - project: "mpib/chm/common/deploy-pipeline"
    ref: "1.8.5"
    file: "python-app.yml"
