variables:
  DEPLOYMENT_VARS: "MONGO_URL, DATABASE_NAME, BACKEND_USER, BACKEND_PASSWORD"
  APP_NAME: rn-iii-backend
  DOCKER_FILE: setup/docker/Dockerfile
  DOCKER_TARGET: backend
  DATABASE_NAME: rn-iii

include:
  - project: "mpib/chm/common/deploy-pipeline"
    ref: "1.8.5"
    file: "python-app.yml"
