variables:
  DEPLOYMENT_VARS: "MONGO_URL, DATABASE_NAME, BACKEND_USER, BACKEND_PASSWORD"
  APP_NAME: rn-iii-backend
  DOCKER_FILE: setup/docker/Dockerfile
  DOCKER_TARGET: backend
  MAIN_URL: rn-iii-backend.eks-test-default.mpg-chm.com # BUG: script fails if not set explicitly
  DATABASE_NAME: "rn-iii-backend-main" # BUG: script fails if not set explicitly

include:
  - project: "mpib/chm/common/deploy-pipeline"
    ref: "1.8.5"
    file: "python-app.yml"
