variables:
  APP_NAME: rn-iii-frontend
  BACKEND_URL: https://rn-iii-backend.eks-test-default.mpg-chm.com
  DOCKER_FILE: setup/docker/Dockerfile-frontend

include:
  - project: "mpib/chm/common/deploy-pipeline"
    ref: "1.8.5"
    file: "react-app.yml"

build:
  # SEE: https://gitlab.com/gitlab-org/gitlab/-/issues/346695
  before_script:
    - "echo Running child pipeline in subdirectory: $CHILD_PIPELINE_EXECUTION_CONTEXT"
    - cd $CHILD_PIPELINE_EXECUTION_CONTEXT
  cache:
    paths:
      - ${CHILD_PIPELINE_EXECUTION_CONTEXT}/node_modules/ # Feature: make frontend path configurable

  artifacts:
    paths:
      - ${CHILD_PIPELINE_EXECUTION_CONTEXT}/dist/ # Feature: make frontend path configurable
    expire_in: 1 week
